### ISSUE TITLE
no bottom padding for footer

### ISSUE THREAD

**Issue by dolbilov** [Project-month/Everland#21]
@fedbka can you please add bottom padding for `footer` section:
![image](https://user-images.githubusercontent.com/22425226/184607313-58be8dd1-e33a-43bb-90b3-9d3b2c124758.png)
![image](https://user-images.githubusercontent.com/22425226/184607026-5219b107-faa8-4aae-b2ac-ef031f1c1a24.png)

**Comment by fedbka** [comment]
@dolbilov, thnx for your attention. I'll fix this until tommorow (16.08.2022)

**Comment by dolbilov** [comment]
Fix it PR #23
