### ISSUE TITLE
rename class: 'optimization' -> 'capital__content'

### ISSUE THREAD

**Issue by fedbka** [Project-month/Everland#37]
I suppose that the name "capital __content" is more appropriate for  CSS-class 'optimization'. It will also allow the css-file to be located in a more suitable folder from the point of view of the BEM-methodology.

**Comment by dolbilov** [comment]
Там нужно очень много менять. Там есть 3 класса: `optimization`, `fit` и `wrapper`. Там нужно переписать это все, на `content`.
